[package]
name = "lab6"
version = "0.1.0"
edition = "2021"

[dependencies]
criterion = "0.5.1"
crossbeam = "0.8.4"
scheduled-thread-pool = "0.2.7"
threadpool = "1.8.1"

[[bench]]
name = "scheduler_ex1_bench"
harness = false
